language: python
python:
  - 2.7

services:
  - docker

install:
    - docker build -t ihar77/cpp-base-builder ./docker_base_builder/
    - sudo docker build -t ihar77/cpp-project-builder .

script:
  - docker images
